### ISSUE TITLE
Handle stopping containers during a test

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/goth#451]
e.g. when calling `await requestor.stop()`:

```
  Traceback (most recent call last):
    File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/nieznanysprawiciel/Repos/Golem/goth/goth/runner/log_monitor.py", line 176, in _buffer_input
      self.add_event(event)
    File "/home/nieznanysprawiciel/Repos/Golem/goth/goth/assertions/monitor.py", line 145, in add_event
      raise RuntimeError(f"Monitor {self.name or ''} is not running")
  RuntimeError: Monitor requestor is not running
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```

Another finding: `Moreover it seems that Provider is able to send DebitNote despite Requestor daemon being killed. It differs from real life, where we get error.`

**Comment by zakaprov** [comment]
We now have a successfully running scenario in which one of the containers gets stopped during the test (https://github.com/golemfactory/yagna/blob/f353e7025acd189f55b7d149779d4cda03d1467d/goth_tests/domain/ya-provider/test_provider_break_agreement.py#L220).
However, that scenario relies on calling the Docker API rather than `Probe.stop()`.
I'm going to close this issue in favour of https://github.com/golemfactory/goth/issues/516.
