### ISSUE TITLE
RuntimeError: Monitor provider-2_ya-provider is not running

### ISSUE THREAD

**Issue by azawlocki** [golemfactory/goth#468]
https://github.com/golemfactory/yapapi/pull/308/checks?check_run_id=2254747885#step:7:127:
```
INFO     [goth.runner                   ] Test finished: test_run_blender
Traceback (most recent call last):
  File "/home/vagrant/.cache/pypoetry/virtualenvs/yapapi-9PyRxJmn-py3.8/lib/python3.8/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
INFO     [goth.runner.proxy             ] Embedded mitmproxy exited
INFO     [goth.runner.probe             ] [provider-2] Stopping probe
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/opt/actions-runner/_work/_tool/Python/3.8.0/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/actions-runner/_work/_tool/Python/3.8.0/x64/lib/python3.8/threading.py", line 870, in run
  File "/home/vagrant/.cache/pypoetry/virtualenvs/yapapi-9PyRxJmn-py3.8/lib/python3.8/site-packages/goth/runner/log_monitor.py", line 201, in _buffer_input
    self.add_event_sync(event)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/yapapi-9PyRxJmn-py3.8/lib/python3.8/site-packages/goth/assertions/monitor.py", line 173, in add_event_sync
    raise RuntimeError(f"Monitor {self.name or ''} is not running")
RuntimeError: Monitor provider-2_ya-provider is not running
```

**Comment by azawlocki** [comment]
A similar error (an `EventMonitor` stopped before stopping a thread that calls its `add_event_sync()` method) may also occur in the proxy, for the monitor for API events. May this be the cause of the `TypeError: 'NoneType' object is not callable` error?
